package com.example.togetthere.utils

import kotlin.to

object FlagUtils {
    val flagEmojis = mapOf(
        "Afghanistan" to "🇦🇫",
        "Albania" to "🇦🇱",
        "Algeria" to "🇩🇿",
        "Andorra" to "🇦🇩",
        "Angola" to "🇦🇴",
        "Antigua and Barbuda" to "🇦🇬",
        "Argentina" to "🇦🇷",
        "Armenia" to "🇦🇲",
        "Australia" to "🇦🇺",
        "Austria" to "🇦🇹",
        "Azerbaijan" to "🇦🇿",
        "Bahamas" to "🇧🇸",
        "Bahrain" to "🇧🇭",
        "Bangladesh" to "🇧🇩",
        "Barbados" to "🇧🇧",
        "Belarus" to "🇧🇾",
        "Belgium" to "🇧🇪",
        "Belize" to "🇧🇿",
        "Benin" to "🇧🇯",
        "Bhutan" to "🇧🇹",
        "Bolivia" to "🇧🇴",
        "Bosnia and Herzegovina" to "🇧🇦",
        "Botswana" to "🇧🇼",
        "Brazil" to "🇧🇷",
        "Brunei" to "🇧🇳",
        "Bulgaria" to "🇧🇬",
        "Burkina Faso" to "🇧🇫",
        "Burundi" to "🇧🇮",
        "Cabo Verde" to "🇨🇻",
        "Cambodia" to "🇰🇭",
        "Cameroon" to "🇨🇲",
        "Canada" to "🇨🇦",
        "Central African Republic" to "🇨🇫",
        "Chad" to "🇹🇩",
        "Chile" to "🇨🇱",
        "China" to "🇨🇳",
        "Colombia" to "🇨🇴",
        "Comoros" to "🇰🇲",
        "Congo (Congo-Brazzaville)" to "🇨🇬",
        "Congo (Democratic Republic)" to "🇨🇩",
        "Costa Rica" to "🇨🇷",
        "Croatia" to "🇭🇷",
        "Cuba" to "🇨🇺",
        "Cyprus" to "🇨🇾",
        "Czech Republic" to "🇨🇿",
        "Denmark" to "🇩🇰",
        "Djibouti" to "🇩🇯",
        "Dominica" to "🇩🇲",
        "Dominican Republic" to "🇩🇴",
        "Ecuador" to "🇪🇨",
        "Egypt" to "🇪🇬",
        "El Salvador" to "🇸🇻",
        "Equatorial Guinea" to "🇬🇶",
        "Eritrea" to "🇪🇷",
        "Estonia" to "🇪🇪",
        "Eswatini" to "🇸🇿",
        "Ethiopia" to "🇪🇹",
        "Fiji" to "🇫🇯",
        "Finland" to "🇫🇮",
        "France" to "🇫🇷",
        "Gabon" to "🇬🇦",
        "Gambia" to "🇬🇲",
        "Georgia" to "🇬🇪",
        "Germany" to "🇩🇪",
        "Ghana" to "🇬🇭",
        "Greece" to "🇬🇷",
        "Grenada" to "🇬🇩",
        "Guatemala" to "🇬🇹",
        "Guinea" to "🇬🇳",
        "Guinea-Bissau" to "🇬🇼",
        "Guyana" to "🇬🇾",
        "Haiti" to "🇭🇹",
        "Honduras" to "🇭🇳",
        "Hungary" to "🇭🇺",
        "Iceland" to "🇮🇸",
        "India" to "🇮🇳",
        "Indonesia" to "🇮🇩",
        "Iran" to "🇮🇷",
        "Iraq" to "🇮🇶",
        "Ireland" to "🇮🇪",
        "Israel" to "🇮🇱",
        "Italy" to "🇮🇹",
        "Jamaica" to "🇯🇲",
        "Japan" to "🇯🇵",
        "Jordan" to "🇯🇴",
        "Kazakhstan" to "🇰🇿",
        "Kenya" to "🇰🇪",
        "Kiribati" to "🇰🇮",
        "Korea, North" to "🇰🇵",
        "Korea, South" to "🇰🇷",
        "Kuwait" to "🇰🇼",
        "Kyrgyzstan" to "🇰🇬",
        "Laos" to "🇱🇸",
        "Latvia" to "🇱🇻",
        "Lebanon" to "🇱🇧",
        "Lesotho" to "🇱🇸",
        "Liberia" to "🇱🇸",
        "Libya" to "🇱🇾",
        "Liechtenstein" to "🇱🇮",
        "Lithuania" to "🇱🇹",
        "Luxembourg" to "🇱🇺",
        "Madagascar" to "🇲🇬",
        "Malawi" to "🇲🇼",
        "Malaysia" to "🇲🇾",
        "Maldives" to "🇲🇻",
        "Mali" to "🇲🇱",
        "Malta" to "🇲🇹",
        "Marshall Islands" to "🇲🇭",
        "Mauritania" to "🇲🇷",
        "Mauritius" to "🇲🇺",
        "Mexico" to "🇲🇽",
        "Micronesia" to "🇫🇲",
        "Moldova" to "🇲🇩",
        "Monaco" to "🇲🇨",
        "Mongolia" to "🇲🇳",
        "Montenegro" to "🇲🇪",
        "Morocco" to "🇲🇦",
        "Mozambique" to "🇲🇿",
        "Myanmar (Burma)" to "🇲🇲",
        "Namibia" to "🇳🇦",
        "Nauru" to "🇳🇷",
        "Nepal" to "🇳🇵",
        "Netherlands" to "🇳🇱",
        "New Zealand" to "🇳🇿",
        "Nicaragua" to "🇳🇮",
        "Niger" to "🇳🇪",
        "Nigeria" to "🇳🇬",
        "North Macedonia" to "🇲🇰",
        "Norway" to "🇳🇴",
        "Oman" to "🇴🇲",
        "Pakistan" to "🇵🇰",
        "Palau" to "🇵🇼",
        "Panama" to "🇵🇦",
        "Papua New Guinea" to "🇵🇬",
        "Paraguay" to "🇵🇾",
        "Peru" to "🇵🇪",
        "Philippines" to "🇵🇭",
        "Poland" to "🇵🇱",
        "Portugal" to "🇵🇹",
        "Qatar" to "🇶🇦",
        "Romania" to "🇷🇴",
        "Russia" to "🇷🇺",
        "Rwanda" to "🇷🇼",
        "Saint Kitts and Nevis" to "🇰🇳",
        "Saint Lucia" to "🇱🇨",
        "Saint Vincent and the Grenadines" to "🇻🇨",
        "Samoa" to "🇼🇸",
        "San Marino" to "🇸🇲",
        "Sao Tome and Principe" to "🇸🇹",
        "Saudi Arabia" to "🇸🇦",
        "Senegal" to "🇸🇳",
        "Serbia" to "🇷🇸",
        "Seychelles" to "🇸🇨",
        "Sierra Leone" to "🇸🇱",
        "Singapore" to "🇸🇬",
        "Slovakia" to "🇸🇰",
        "Slovenia" to "🇸🇮",
        "Solomon Islands" to "🇸🇧",
        "Somalia" to "🇸🇴",
        "South Africa" to "🇿🇦",
        "South Sudan" to "🇸🇸",
        "Spain" to "🇪🇸",
        "Sri Lanka" to "🇱🇰",
        "Sudan" to "🇸🇩",
        "Suriname" to "🇸🇷",
        "Sweden" to "🇸🇪",
        "Switzerland" to "🇨🇭",
        "Syria" to "🇸🇾",
        "Taiwan" to "🇹🇼",
        "Tajikistan" to "🇹🇯",
        "Tanzania" to "🇹🇿",
        "Thailand" to "🇹🇭",
        "Timor-Leste" to "🇹🇱",
        "Togo" to "🇹🇬",
        "Tonga" to "🇹🇴",
        "Trinidad and Tobago" to "🇹🇹",
        "Tunisia" to "🇹🇳",
        "Turkey" to "🇹🇷",
        "Turkmenistan" to "🇹🇲",
        "Tuvalu" to "🇹🇻",
        "Uganda" to "🇺🇬",
        "Ukraine" to "🇺🇦",
        "United Arab Emirates" to "🇦🇪",
        "United Kingdom" to "🇬🇧",
        "United States" to "🇺🇸",
        "Uruguay" to "🇺🇾",
        "Uzbekistan" to "🇺🇿",
        "Vanuatu" to "🇻🇺",
        "Vatican City" to "🇻🇦",
        "Venezuela" to "🇻🇪",
        "Vietnam" to "🇻🇳",
        "Yemen" to "🇾🇪",
        "Zambia" to "🇿🇲",
        "Zimbabwe" to "🇿🇼"
    )

    fun getFlagEmoji(country: String): String {
        return flagEmojis[country] ?: "🏳️‍🌈"
    }
}